# Generated by Django 5.1.3 on 2026-07-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Business Name')),
                ('category', models.CharField(choices=[('retail', 'Retail Shop'), ('grocery', 'Grocery Store'), ('restaurant', 'Restaurant & Food'), ('electronics', 'Electronics'), ('clothing', 'Clothing & Fashion'), ('pharmacy', 'Pharmacy'), ('hardware', 'Hardware & Building Materials'), ('bakery', 'Bakery & Sweets'), ('salon', 'Salon & Spa'), ('automobile', 'Automobile & Repair'), ('stationery', 'Stationery & Books'), ('jewellery', 'Jewellery'), ('other', 'Other')], default='other', max_length=20)),
                ('address', models.TextField(help_text='Full shop/business address')),
                ('phone_number', models.CharField(help_text='Contact number, e.g. 9876543210', max_length=15)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Image URL')),
                ('description', models.TextField(blank=True, help_text='Optional short description of the business')),
                ('is_featured', models.BooleanField(default=False, help_text='Show this business on the homepage')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this listing from the site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
                'ordering': ['-is_featured', 'name'],
            },
        ),
    ]
