# Generated by Django 5.1.3 on 2026-07-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Property Title')),
                ('property_type', models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent'), ('apartment', 'Apartment / Flat'), ('villa', 'Villa / Independent House'), ('plot', 'Plot / Land'), ('commercial', 'Commercial Space'), ('pg', 'PG / Hostel'), ('other', 'Other')], default='sale', max_length=20, verbose_name='Type')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price (₹)')),
                ('location', models.CharField(help_text='Area / locality in Kuppam', max_length=200)),
                ('contact_number', models.CharField(help_text='Contact number, e.g. 9876543210', max_length=15, verbose_name='Contact')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Image URL')),
                ('description', models.TextField(blank=True, help_text='Optional details about the property')),
                ('is_featured', models.BooleanField(default=False, help_text='Show this property on the homepage')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this listing from the site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
