# Generated by Django 5.1.3 on 2026-07-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, verbose_name='Company')),
                ('job_title', models.CharField(max_length=200, verbose_name='Job Title')),
                ('location', models.CharField(help_text='Job location in Kuppam', max_length=200)),
                ('salary', models.CharField(blank=True, help_text='e.g. ₹15,000 - ₹25,000/month, or "Negotiable"', max_length=100)),
                ('contact_number', models.CharField(help_text='Contact number, e.g. 9876543210', max_length=15, verbose_name='Contact')),
                ('description', models.TextField(blank=True, help_text='Optional job description, requirements, etc.')),
                ('is_featured', models.BooleanField(default=False, help_text='Show this job on the homepage')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to close/hide this job listing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
