# Generated by Django 5.1.3 on 2026-07-27 09:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Event Title')),
                ('event_date', models.DateField(verbose_name='Event Date')),
                ('location', models.CharField(help_text='Venue / location in Kuppam', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional details about the event')),
                ('contact_number', models.CharField(blank=True, max_length=15, verbose_name='Contact')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Image URL')),
                ('is_featured', models.BooleanField(default=False, help_text='Show this event on the homepage')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this event from the site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='News Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('published_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Published Date')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Image URL')),
                ('source', models.CharField(blank=True, help_text='Optional source/author name', max_length=150)),
                ('is_featured', models.BooleanField(default=False, help_text='Show this article on the homepage')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this article from the site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News',
                'ordering': ['-published_date'],
            },
        ),
    ]
