# Generated by Django 5.1.3 on 2026-07-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_event_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a photo (takes priority over Image URL below if both are set)', null=True, upload_to='businesses/'),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a photo (takes priority over Image URL below if both are set)', null=True, upload_to='events/'),
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a photo (takes priority over Image URL below if both are set)', null=True, upload_to='news/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a photo (takes priority over Image URL below if both are set)', null=True, upload_to='properties/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.CharField(choices=[('retail', 'Retail Shop'), ('grocery', 'Grocery Store'), ('restaurant', 'Restaurant & Food'), ('electronics', 'Electronics'), ('clothing', 'Clothing & Fashion'), ('pharmacy', 'Pharmacy'), ('hardware', 'Hardware & Building Materials'), ('bakery', 'Bakery & Sweets'), ('salon', 'Salon & Spa'), ('automobile', 'Automobile & Repair'), ('stationery', 'Stationery & Books'), ('jewellery', 'Jewellery'), ('hospital', 'Hospital'), ('education', 'Education'), ('transport', 'Transport'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
