# Generated by Django 5.1.3 on 2026-07-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.CharField(choices=[('retail', 'Retail Shop'), ('grocery', 'Grocery Store'), ('restaurant', 'Restaurant & Food'), ('electronics', 'Electronics'), ('clothing', 'Clothing & Fashion'), ('pharmacy', 'Pharmacy'), ('hardware', 'Hardware & Building Materials'), ('bakery', 'Bakery & Sweets'), ('salon', 'Salon & Spa'), ('automobile', 'Automobile & Repair'), ('stationery', 'Stationery & Books'), ('jewellery', 'Jewellery'), ('hospital', 'Hospital'), ('school', 'School'), ('college', 'College'), ('transport', 'Transport'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
