# Generated by Django 5.1.3 on 2026-07-29 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0010_alter_business_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='listing_model',
            field=models.CharField(choices=[('business', 'Business'), ('property', 'Property'), ('job', 'Job'), ('event', 'Event'), ('news', 'News'), ('project', 'Project')], help_text='Which listing table this category publishes into', max_length=20),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'core'), ('model', 'business')), models.Q(('app_label', 'core'), ('model', 'property')), models.Q(('app_label', 'core'), ('model', 'job')), models.Q(('app_label', 'core'), ('model', 'event')), models.Q(('app_label', 'core'), ('model', 'news')), models.Q(('app_label', 'core'), ('model', 'project')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'core'), ('model', 'business')), models.Q(('app_label', 'core'), ('model', 'property')), models.Q(('app_label', 'core'), ('model', 'job')), models.Q(('app_label', 'core'), ('model', 'event')), models.Q(('app_label', 'core'), ('model', 'news')), models.Q(('app_label', 'core'), ('model', 'project')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='like',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'core'), ('model', 'business')), models.Q(('app_label', 'core'), ('model', 'property')), models.Q(('app_label', 'core'), ('model', 'job')), models.Q(('app_label', 'core'), ('model', 'event')), models.Q(('app_label', 'core'), ('model', 'news')), models.Q(('app_label', 'core'), ('model', 'project')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'core'), ('model', 'business')), models.Q(('app_label', 'core'), ('model', 'property')), models.Q(('app_label', 'core'), ('model', 'job')), models.Q(('app_label', 'core'), ('model', 'event')), models.Q(('app_label', 'core'), ('model', 'news')), models.Q(('app_label', 'core'), ('model', 'project')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='report',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'core'), ('model', 'business')), models.Q(('app_label', 'core'), ('model', 'property')), models.Q(('app_label', 'core'), ('model', 'job')), models.Q(('app_label', 'core'), ('model', 'event')), models.Q(('app_label', 'core'), ('model', 'news')), models.Q(('app_label', 'core'), ('model', 'project')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='review',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'core'), ('model', 'business')), models.Q(('app_label', 'core'), ('model', 'property')), models.Q(('app_label', 'core'), ('model', 'job')), models.Q(('app_label', 'core'), ('model', 'event')), models.Q(('app_label', 'core'), ('model', 'news')), models.Q(('app_label', 'core'), ('model', 'project')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='share',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'core'), ('model', 'business')), models.Q(('app_label', 'core'), ('model', 'property')), models.Q(('app_label', 'core'), ('model', 'job')), models.Q(('app_label', 'core'), ('model', 'event')), models.Q(('app_label', 'core'), ('model', 'news')), models.Q(('app_label', 'core'), ('model', 'project')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('changes_requested', 'Changes Requested')], default='approved', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=220, null=True, unique=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('share_count', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200, verbose_name='Project Title')),
                ('project_status', models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='planned', max_length=20, verbose_name='Status')),
                ('location', models.CharField(help_text='Area / locality in Kuppam', max_length=200)),
                ('expected_completion', models.DateField(blank=True, help_text='Optional expected completion date', null=True)),
                ('department', models.CharField(blank=True, help_text='Optional executing department/agency', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Optional details about the project')),
                ('image', models.ImageField(blank=True, help_text='Upload a photo (takes priority over Image URL below if both are set)', null=True, upload_to='projects/')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Image URL')),
                ('is_featured', models.BooleanField(default=False, help_text='Show this project on the homepage')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this project from the site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_listings', to='core.category')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_listings', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Upcoming Project',
                'verbose_name_plural': 'Upcoming Projects',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
