# Generated by Django 5.1.3 on 2026-08-01 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_contactmessage_newslettersubscriber'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_palette', models.CharField(choices=[('default', 'Default (OneTownCity Amber)'), ('summer-silk', 'Summer Silk'), ('rainy-velvet', 'Rainy Velvet'), ('nordic-aurora', 'Nordic Aurora')], default='default', max_length=20)),
                ('enforce_palette', models.BooleanField(default=False, help_text="When on, visitors can't override this with their own theme switcher.")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
