# Generated by Django 5.1.3 on 2026-08-01 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0014_sitesettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Leave blank for a top-level category; set this to nest as a subcategory.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='listing_model',
            field=models.CharField(blank=True, choices=[('business', 'Business'), ('property', 'Property'), ('job', 'Job'), ('event', 'Event'), ('news', 'News'), ('project', 'Project')], help_text="Which listing table this category publishes into. Subcategories inherit their parent's value automatically if left blank.", max_length=20),
        ),
        migrations.CreateModel(
            name='PostVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('video', models.FileField(upload_to='post_gallery_videos/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'core'), ('model', 'business')), models.Q(('app_label', 'core'), ('model', 'property')), models.Q(('app_label', 'core'), ('model', 'job')), models.Q(('app_label', 'core'), ('model', 'event')), models.Q(('app_label', 'core'), ('model', 'news')), models.Q(('app_label', 'core'), ('model', 'project')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_postvi_content_fcc680_idx')],
            },
        ),
        migrations.CreateModel(
            name='TranslationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('field_name', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=5)),
                ('source_text', models.TextField()),
                ('translated_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'core'), ('model', 'business')), models.Q(('app_label', 'core'), ('model', 'property')), models.Q(('app_label', 'core'), ('model', 'job')), models.Q(('app_label', 'core'), ('model', 'event')), models.Q(('app_label', 'core'), ('model', 'news')), models.Q(('app_label', 'core'), ('model', 'project')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Translation cache entry',
                'verbose_name_plural': 'Translation cache entries',
                'indexes': [models.Index(fields=['content_type', 'object_id', 'field_name', 'language'], name='core_transl_content_380fce_idx')],
                'unique_together': {('content_type', 'object_id', 'field_name', 'language')},
            },
        ),
    ]
