# Generated by Django 5.1.3 on 2026-08-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_category_parent_alter_category_listing_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, help_text='Short blurb shown on the homepage service card (top-level categories only).', max_length=300),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.CharField(blank=True, help_text="Static path for the homepage service card, e.g. 'images/services/real-estate.jpg'", max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_palette',
            field=models.CharField(choices=[('default', 'Default (OneTownCity Amber)'), ('summer-silk', 'Summer Silk'), ('rainy-velvet', 'Rainy Velvet'), ('nordic-aurora', 'Nordic Aurora'), ('winter', 'Snow (Christmas)'), ('spring', 'Spring'), ('autumn', 'Autumn')], default='default', max_length=20),
        ),
    ]
