# Generated by Django 5.1.3 on 2026-08-02 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0017_restructure_category_hierarchy'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'core'), ('model', 'business')), models.Q(('app_label', 'core'), ('model', 'property')), models.Q(('app_label', 'core'), ('model', 'job')), models.Q(('app_label', 'core'), ('model', 'event')), models.Q(('app_label', 'core'), ('model', 'news')), models.Q(('app_label', 'core'), ('model', 'project')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_postvi_content_f26126_idx'), models.Index(fields=['created_at'], name='core_postvi_created_d59e25_idx')],
            },
        ),
    ]
