# Generated by Django 5.1.3 on 2026-08-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_pushsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('listing_approved', 'Listing Approved'), ('listing_rejected', 'Listing Rejected'), ('listing_changes_requested', 'Listing Changes Requested'), ('listing_submitted', 'New Listing Submitted'), ('listing_deleted', 'Listing Deleted'), ('admin_request_submitted', 'New Admin Request'), ('admin_request_approved', 'Admin Request Approved'), ('admin_request_rejected', 'Admin Request Rejected'), ('admin_request_changes_requested', 'Admin Request Changes Requested'), ('new_comment', 'New Comment'), ('new_review', 'New Review')], max_length=40),
        ),
    ]
