# Generated by Django 5.2.17 on 2026-08-24 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('country', 'Country'), ('state', 'State'), ('district', 'District'), ('city', 'City'), ('locality', 'Locality / Area')], max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='core.location')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='business',
            name='city',
            field=models.ForeignKey(blank=True, help_text='Canonical city for this listing. Leave blank only for legacy data pending classification.', limit_choices_to={'kind': 'city'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_listings', to='core.location'),
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.ForeignKey(blank=True, help_text='Canonical city for this listing. Leave blank only for legacy data pending classification.', limit_choices_to={'kind': 'city'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_listings', to='core.location'),
        ),
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.ForeignKey(blank=True, help_text='Canonical city for this listing. Leave blank only for legacy data pending classification.', limit_choices_to={'kind': 'city'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_listings', to='core.location'),
        ),
        migrations.AddField(
            model_name='news',
            name='city',
            field=models.ForeignKey(blank=True, help_text='Canonical city for this listing. Leave blank only for legacy data pending classification.', limit_choices_to={'kind': 'city'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_listings', to='core.location'),
        ),
        migrations.AddField(
            model_name='project',
            name='city',
            field=models.ForeignKey(blank=True, help_text='Canonical city for this listing. Leave blank only for legacy data pending classification.', limit_choices_to={'kind': 'city'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_listings', to='core.location'),
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.ForeignKey(blank=True, help_text='Canonical city for this listing. Leave blank only for legacy data pending classification.', limit_choices_to={'kind': 'city'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_listings', to='core.location'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('parent', 'kind', 'name'), name='unique_location_in_parent'),
        ),
    ]
