# Generated by Django 5.2.17 on 2026-08-24 16:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_seed_location_coordinates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['status', 'is_active', 'city'], name='core_busine_status_0a6e79_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'is_active', 'city'], name='core_event_status_342e60_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'is_active', 'city'], name='core_job_status_4224f6_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['status', 'is_active', 'city'], name='core_news_status_7366dc_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'is_active', 'city'], name='core_projec_status_d66449_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'is_active', 'city'], name='core_proper_status_a5414c_idx'),
        ),
    ]
