# Generated by Django 5.2.17 on 2026-08-25 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_rename_businesses_category'),
        ('core', '0025_business_core_busine_status_0a6e79_idx_and_more'),
    ]

    operations = [
    ]
