# Generated by Django 5.2.17 on 2026-09-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_business_status_alter_event_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Precise pin location, e.g. set via 'Use my current location' on the listing form. Powers distance-based 'near me' search (currently used for Repair Services).", max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.CharField(choices=[('retail', 'Retail Shop'), ('grocery', 'Grocery Store'), ('restaurant', 'Restaurant & Food'), ('electronics', 'Electronics'), ('clothing', 'Clothing & Fashion'), ('pharmacy', 'Pharmacy'), ('hardware', 'Hardware & Building Materials'), ('bakery', 'Bakery & Sweets'), ('salon', 'Salon & Spa'), ('automobile', 'Automobile & Repair'), ('stationery', 'Stationery & Books'), ('jewellery', 'Jewellery'), ('hospital', 'Hospital'), ('school', 'School'), ('college', 'College'), ('transport', 'Transport'), ('repair', 'Repair Services'), ('tourism', 'Places to Visit'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
