# Generated by Django 5.2.17 on 2026-09-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_repair_tourism_top_level_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['event_date', 'event_time'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AddField(
            model_name='event',
            name='event_time',
            field=models.TimeField(blank=True, help_text='Optional — when in the day it starts, e.g. 6:00 PM', null=True, verbose_name='Start Time'),
        ),
    ]
