# Generated by Django 5.2.17 on 2026-09-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_event_options_event_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('regular', 'Regular / Full-Time'), ('hourly', 'Hourly Basis')], default='regular', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='shift_date',
            field=models.DateField(blank=True, help_text="Optional — which date this job/shift is needed, e.g. for an Hourly Basis job. Powers the 'available on this date' filter on the Jobs page.", null=True, verbose_name='Shift Date'),
        ),
        migrations.AddField(
            model_name='job',
            name='shift_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Shift End Time'),
        ),
        migrations.AddField(
            model_name='job',
            name='shift_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Shift Start Time'),
        ),
    ]
