# Generated by Django 5.2.17 on 2026-09-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_backfill_missing_city_to_kuppam'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='working_hours',
            field=models.CharField(blank=True, help_text="e.g. 'Mon–Sat: 9:00 AM – 8:00 PM, Sun: Closed'", max_length=150),
        ),
        migrations.AlterField(
            model_name='business',
            name='website',
            field=models.URLField(blank=True, help_text='Website or social media page (Facebook, Instagram, etc.)', max_length=300),
        ),
    ]
