# Generated by Django 5.2.17 on 2026-09-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_seed_job_type_subcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='working_days_hours',
            field=models.JSONField(blank=True, default=dict, help_text="Structured schedule set via the working-days/hours picker on the listing form: {'mon': {'open': '09:00', 'close': '18:00'}, ...} — a day absent from the dict means closed. working_hours above is auto-derived from this."),
        ),
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Precise pin location, e.g. set via 'Use my current location' on the listing form.", max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='maps_link',
            field=models.URLField(blank=True, max_length=500, verbose_name='Google Maps Link'),
        ),
        migrations.AddField(
            model_name='job',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Precise pin location, e.g. set via 'Use my current location' on the listing form.", max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='maps_link',
            field=models.URLField(blank=True, max_length=500, verbose_name='Google Maps Link'),
        ),
        migrations.AddField(
            model_name='project',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Precise pin location, e.g. set via 'Use my current location' on the listing form.", max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='maps_link',
            field=models.URLField(blank=True, max_length=500, verbose_name='Google Maps Link'),
        ),
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Precise pin location, e.g. set via 'Use my current location' on the listing form.", max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='maps_link',
            field=models.URLField(blank=True, max_length=500, verbose_name='Google Maps Link'),
        ),
        migrations.AlterField(
            model_name='business',
            name='working_hours',
            field=models.CharField(blank=True, help_text="e.g. 'Mon–Sat: 9:00 AM – 8:00 PM, Sun: Closed'. Auto-filled from working_days_hours below when that's set — see save().", max_length=150),
        ),
    ]
