# Generated by Django 5.2.17 on 2026-09-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_seed_job_type_subcategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.CharField(choices=[('retail', 'Retail Shop'), ('grocery', 'Grocery Store'), ('restaurant', 'Restaurant & Food'), ('electronics', 'Electronics'), ('clothing', 'Clothing & Fashion'), ('pharmacy', 'Pharmacy'), ('hardware', 'Hardware & Building Materials'), ('bakery', 'Bakery & Sweets'), ('salon', 'Salon & Spa'), ('automobile', 'Automobile & Repair'), ('stationery', 'Stationery & Books'), ('jewellery', 'Jewellery'), ('hospital', 'Hospital'), ('school', 'School'), ('college', 'College'), ('transport', 'Transport'), ('repair', 'Repair Services'), ('tourism', 'Places to Visit'), ('tuition_center', 'Tuition & Coaching Centers'), ('marketplace', 'Buy / Sell / Exchange'), ('student_services', 'Student Services'), ('scholarship_scheme', 'Scholarships & Govt. Schemes'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
