# Generated by Django 5.2.17 on 2026-09-08 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_business_category'),
        ('core', '0042_seed_village_happenings_category'),
    ]

    operations = [
    ]
