# Generated by Django 5.2.17 on 2026-09-08 13:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0044_seed_student_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='listing_model',
            field=models.CharField(blank=True, choices=[('business', 'Business'), ('property', 'Property'), ('job', 'Job'), ('event', 'Event'), ('news', 'News'), ('project', 'Project'), ('scholarship', 'Scholarship / Government Scheme'), ('lostfound', 'Lost & Found')], help_text="Which listing table this category publishes into. Subcategories inherit their parent's value automatically if left blank.", max_length=20),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'core'), ('model', 'business')), models.Q(('app_label', 'core'), ('model', 'property')), models.Q(('app_label', 'core'), ('model', 'job')), models.Q(('app_label', 'core'), ('model', 'event')), models.Q(('app_label', 'core'), ('model', 'news')), models.Q(('app_label', 'core'), ('model', 'project')), models.Q(('app_label', 'core'), ('model', 'scholarship')), models.Q(('app_label', 'core'), ('model', 'lostfound')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'core'), ('model', 'business')), models.Q(('app_label', 'core'), ('model', 'property')), models.Q(('app_label', 'core'), ('model', 'job')), models.Q(('app_label', 'core'), ('model', 'event')), models.Q(('app_label', 'core'), ('model', 'news')), models.Q(('app_label', 'core'), ('model', 'project')), models.Q(('app_label', 'core'), ('model', 'scholarship')), models.Q(('app_label', 'core'), ('model', 'lostfound')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='like',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'core'), ('model', 'business')), models.Q(('app_label', 'core'), ('model', 'property')), models.Q(('app_label', 'core'), ('model', 'job')), models.Q(('app_label', 'core'), ('model', 'event')), models.Q(('app_label', 'core'), ('model', 'news')), models.Q(('app_label', 'core'), ('model', 'project')), models.Q(('app_label', 'core'), ('model', 'scholarship')), models.Q(('app_label', 'core'), ('model', 'lostfound')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'core'), ('model', 'business')), models.Q(('app_label', 'core'), ('model', 'property')), models.Q(('app_label', 'core'), ('model', 'job')), models.Q(('app_label', 'core'), ('model', 'event')), models.Q(('app_label', 'core'), ('model', 'news')), models.Q(('app_label', 'core'), ('model', 'project')), models.Q(('app_label', 'core'), ('model', 'scholarship')), models.Q(('app_label', 'core'), ('model', 'lostfound')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='postvideo',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'core'), ('model', 'business')), models.Q(('app_label', 'core'), ('model', 'property')), models.Q(('app_label', 'core'), ('model', 'job')), models.Q(('app_label', 'core'), ('model', 'event')), models.Q(('app_label', 'core'), ('model', 'news')), models.Q(('app_label', 'core'), ('model', 'project')), models.Q(('app_label', 'core'), ('model', 'scholarship')), models.Q(('app_label', 'core'), ('model', 'lostfound')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='postview',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'core'), ('model', 'business')), models.Q(('app_label', 'core'), ('model', 'property')), models.Q(('app_label', 'core'), ('model', 'job')), models.Q(('app_label', 'core'), ('model', 'event')), models.Q(('app_label', 'core'), ('model', 'news')), models.Q(('app_label', 'core'), ('model', 'project')), models.Q(('app_label', 'core'), ('model', 'scholarship')), models.Q(('app_label', 'core'), ('model', 'lostfound')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='report',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'core'), ('model', 'business')), models.Q(('app_label', 'core'), ('model', 'property')), models.Q(('app_label', 'core'), ('model', 'job')), models.Q(('app_label', 'core'), ('model', 'event')), models.Q(('app_label', 'core'), ('model', 'news')), models.Q(('app_label', 'core'), ('model', 'project')), models.Q(('app_label', 'core'), ('model', 'scholarship')), models.Q(('app_label', 'core'), ('model', 'lostfound')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='review',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'core'), ('model', 'business')), models.Q(('app_label', 'core'), ('model', 'property')), models.Q(('app_label', 'core'), ('model', 'job')), models.Q(('app_label', 'core'), ('model', 'event')), models.Q(('app_label', 'core'), ('model', 'news')), models.Q(('app_label', 'core'), ('model', 'project')), models.Q(('app_label', 'core'), ('model', 'scholarship')), models.Q(('app_label', 'core'), ('model', 'lostfound')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='share',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'core'), ('model', 'business')), models.Q(('app_label', 'core'), ('model', 'property')), models.Q(('app_label', 'core'), ('model', 'job')), models.Q(('app_label', 'core'), ('model', 'event')), models.Q(('app_label', 'core'), ('model', 'news')), models.Q(('app_label', 'core'), ('model', 'project')), models.Q(('app_label', 'core'), ('model', 'scholarship')), models.Q(('app_label', 'core'), ('model', 'lostfound')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='translationcache',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'core'), ('model', 'business')), models.Q(('app_label', 'core'), ('model', 'property')), models.Q(('app_label', 'core'), ('model', 'job')), models.Q(('app_label', 'core'), ('model', 'event')), models.Q(('app_label', 'core'), ('model', 'news')), models.Q(('app_label', 'core'), ('model', 'project')), models.Q(('app_label', 'core'), ('model', 'scholarship')), models.Q(('app_label', 'core'), ('model', 'lostfound')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.CreateModel(
            name='LostFound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('changes_requested', 'Changes Requested')], default='approved', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=220, null=True, unique=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('share_count', models.PositiveIntegerField(default=0)),
                ('report_type', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], max_length=10, verbose_name='Lost or Found')),
                ('title', models.CharField(help_text="Short description, e.g. 'Black leather wallet'", max_length=200)),
                ('item_category', models.CharField(choices=[('electronics', 'Electronics'), ('documents', 'Documents / ID Cards'), ('bag_wallet', 'Bag / Wallet'), ('jewellery', 'Jewellery'), ('keys', 'Keys'), ('pet', 'Pet'), ('clothing', 'Clothing'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date lost/found')),
                ('location', models.CharField(help_text="Where it was lost/found, e.g. 'Near Kuppam Bus Stand'", max_length=200)),
                ('contact_number', models.CharField(blank=True, help_text='Optional — shown publicly on this post if provided. Leave blank to be reachable only through comments.', max_length=15)),
                ('image', models.ImageField(blank=True, help_text='A photo of the item (or a similar one) helps a lot', null=True, upload_to='lost_found/')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Image URL')),
                ('is_resolved', models.BooleanField(default=False, help_text='Mark resolved once the item has been returned / reunited with its owner')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this listing from the site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, help_text='Canonical city for this listing. Leave blank only for legacy data pending classification.', limit_choices_to={'kind': 'city'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_listings', to='core.location')),
                ('listing_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_listings', to='core.category')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_listings', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lost & Found Item',
                'verbose_name_plural': 'Lost & Found Items',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'is_active', 'city'], name='core_lostfo_status_829e87_idx')],
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('changes_requested', 'Changes Requested')], default='approved', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=220, null=True, unique=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('share_count', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200, verbose_name='Scholarship / Scheme Title')),
                ('scholarship_type', models.CharField(choices=[('government', 'Government Scheme'), ('merit', 'Merit-based'), ('need_based', 'Need-based'), ('minority', 'Minority / Community'), ('sports', 'Sports'), ('research', 'Research / Fellowship'), ('other', 'Other')], default='other', max_length=20, verbose_name='Type')),
                ('provider', models.CharField(help_text="Issuing authority, e.g. 'Government of Andhra Pradesh' or 'Reliance Foundation'", max_length=200, verbose_name='Provider / Authority')),
                ('description', models.TextField(blank=True, help_text='What this scholarship/scheme covers')),
                ('eligibility', models.TextField(blank=True, help_text='Who can apply')),
                ('application_deadline', models.DateField(blank=True, help_text='Leave blank if the scheme has no fixed deadline / is open year-round', null=True)),
                ('official_url', models.URLField(blank=True, help_text='Link to the real official application/information page — never a placeholder or invented link', max_length=500, verbose_name='Official URL')),
                ('contact_number', models.CharField(blank=True, help_text='Optional helpline/contact number', max_length=15)),
                ('image', models.ImageField(blank=True, help_text='Upload a photo (takes priority over Image URL below if both are set)', null=True, upload_to='scholarships/')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Image URL')),
                ('is_featured', models.BooleanField(default=False, help_text='Show this scholarship on the homepage')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this listing from the site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, help_text='Canonical city for this listing. Leave blank only for legacy data pending classification.', limit_choices_to={'kind': 'city'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_listings', to='core.location')),
                ('listing_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_listings', to='core.category')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_listings', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scholarship / Government Scheme',
                'verbose_name_plural': 'Scholarships & Government Schemes',
                'ordering': ['-is_featured', 'application_deadline', '-created_at'],
                'indexes': [models.Index(fields=['status', 'is_active', 'city'], name='core_schola_status_a6dff9_idx')],
            },
        ),
    ]
