# Generated by Django 5.2.17 on 2026-09-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_mobiledevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='adult_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='When the user confirmed they are 18 or older', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, help_text='When the user accepted the Terms of Service and Privacy Policy', null=True),
        ),
    ]
