# Generated by Django 5.2.17 on 2026-10-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_merge_student_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, help_text='Set when the user deactivates their own account; cleared automatically when they sign in again', null=True),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='event_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('deactivate', 'Deactivated'), ('reactivate', 'Reactivated')], max_length=10),
        ),
    ]
